# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
    -   id: detect-private-key
    -   id: check-toml
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.1
    hooks:
    -   id: codespell
        name: codespell
        description: Checks for common misspellings in text files.
        entry: codespell
        language: python
        types: [text]
-   repo: https://github.com/sondrelg/pep585-upgrade
    rev: "v1.0" # Use the sha / tag you want to point at
    hooks:
    -   id: upgrade-type-hints
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.38.2
    hooks:
    -   id: pyupgrade
        args: ["--py39-plus"]
-   repo: local
    hooks:
    -   id: autoflake
        name: autoflake
        entry: autoflake
        language: python
        types: [python]
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable', '--ignore-init-module-imports']
    -   id: black
        name: black
        entry: black
        language: python
        types: [python]
        language_version: python3.9
        args: [--quiet]
    -   id: isort
        name: isort
        entry: isort
        language: python
        types: [python]
        args: ["--profile", "black", "--filter-files"]
    -   id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
    -   id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [python]
